import Login from "./Login";
import GioiThieu from "./GioiThieu";
import DeTai from "./DeTai";
import Signup from "./Singup";
import AdminQuanly from "./AdminQuanly";
import UserDangky from "./UserDangky";
import UserQuanLy from "./UserQuanLy";
import QuanLythongtin from "./QuanLythongtin";
import Hopthu from "./Hopthu";
export { Login, GioiThieu, DeTai, Signup, AdminQuanly, UserDangky, UserQuanLy, QuanLythongtin, Hopthu };
